# Site settings
title: Tanzfunktion
email: your-email@domain.com
description: ""
baseurl: ""
url: "http://tanzfunktion.de"

# Build settings
markdown: kramdown
permalink: pretty
paginate: 5

admin:
  github_username: tanzfunktion
  github_repo: tanzfunktion.github.io
  soundcloud_client_id: 0686300807bd25cd798c519f70192c31
