# Site settings
title: Your soundblog
email: your-email@domain.com
description: "Your soundblog description"
baseurl: ""
url: "http://yourdomain.com"
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
permalink: pretty
paginate: 5
